version: '3.4'

services:
  athena:
    image: athenaos/core
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    secrets:
       - source: htb-api
    sysctls:
       - net.ipv6.conf.all.disable_ipv6=0
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped

secrets:
  htb-api:
    file: ./htb-api-file
