name: Scheduled Publish

on:
  schedule:
    - cron: '22 4 * * 0'
  workflow_dispatch:

env:
  CORE_IMG: core

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  publish:
    runs-on: ubuntu-latest
    container:
      image: docker.io/athenaos/base-devel

    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: pacman -Sy --noconfirm --needed docker

      - name: Build core
        run: |
          docker build . --file ./Dockerfile --tag docker.io/athenaos/$CORE_IMG

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image
        run: |
          docker push docker.io/athenaos/$CORE_IMG
